---
services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: idpcore
      POSTGRES_PASSWORD: idpcore_password
    ports:
      - "5437:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
