--- This migration creates the audit tables for Envers. It is designed to be compatible with the default Envers configuration, which uses a single revision table (envers_transaction_log) and a revinfo table that references it. The audit tables for entities, properties, relations, and templates are created with foreign keys referencing the revision number in the transaction log.
-- The revision number is generated using an identity column.
-- The revtype column in the audit tables indicates the type of revision (0 for addition, 1 for modification, 2 for deletion), which is standard in Envers to track the nature of changes.
-- Indexes are created on the revision number and other relevant columns to optimize query performance when retrieving audit data.
-- Note: The actual structure of the audit tables may need to be adjusted based on the specific entities and properties used in the application, but this provides a general framework for implementing Envers auditing in a PostgreSQL database.

CREATE TABLE envers_transaction_log
(
    rev                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_timestamp BIGINT NOT NULL,
    auth_id            VARCHAR(255)
);

-- Envers will automatically insert the names of the JPA Entity classes modified in each transaction here.
CREATE TABLE envers_modified_entities
(
    rev         BIGINT       NOT NULL,
    entity_name VARCHAR(255) NOT NULL,
    PRIMARY KEY (rev, entity_name),
    CONSTRAINT fk_envers_modified_entities_rev FOREIGN KEY (rev) REFERENCES envers_transaction_log (rev) ON DELETE CASCADE
);

CREATE INDEX idx_transaction_log_timestamp ON envers_transaction_log (revision_timestamp);
CREATE INDEX idx_transaction_log_auth_id ON envers_transaction_log (auth_id);

CREATE TABLE entity_aud
(
    id                      UUID   NOT NULL,
    rev                     BIGINT NOT NULL,
    revtype                 SMALLINT,
    template_identifier     VARCHAR(255),
    template_identifier_mod BOOLEAN,
    name                    VARCHAR(255),
    name_mod                BOOLEAN,
    identifier              VARCHAR(255),
    identifier_mod          BOOLEAN,
    properties_mod          BOOLEAN,
    relations_mod           BOOLEAN,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_entity_aud_revinfo FOREIGN KEY (rev) REFERENCES envers_transaction_log (rev) ON DELETE CASCADE
);

CREATE INDEX idx_entity_aud_rev ON entity_aud (rev);
CREATE INDEX idx_entity_aud_template_identifier_identifier ON entity_aud (template_identifier, identifier);

CREATE TABLE property_aud
(
    id        UUID   NOT NULL,
    rev       BIGINT NOT NULL,
    revtype   SMALLINT,
    name      VARCHAR(255),
    name_mod  BOOLEAN,
    value     VARCHAR(255),
    value_mod BOOLEAN,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_property_aud_revinfo FOREIGN KEY (rev) REFERENCES envers_transaction_log (rev) ON DELETE CASCADE
);

CREATE INDEX idx_property_aud_rev ON property_aud (rev);

CREATE TABLE relation_aud
(
    id                             UUID   NOT NULL,
    rev                            BIGINT NOT NULL,
    revtype                        SMALLINT,
    name                           VARCHAR(255),
    name_mod                       BOOLEAN,
    target_template_identifier     VARCHAR(255),
    target_template_identifier_mod BOOLEAN,
    target_entities_mod            BOOLEAN,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_relation_aud_revinfo FOREIGN KEY (rev) REFERENCES envers_transaction_log (rev) ON DELETE CASCADE
);

CREATE INDEX idx_relation_aud_rev ON relation_aud (rev);

CREATE TABLE entity_template_aud
(
    id              UUID   NOT NULL,
    rev             BIGINT NOT NULL,
    revtype         SMALLINT,
    identifier      VARCHAR(255),
    identifier_mod BOOLEAN,
    name            VARCHAR(255),
    name_mod        BOOLEAN,
    description     TEXT,
    description_mod BOOLEAN,
    properties_definitions_mod BOOLEAN,
    relations_definitions_mod  BOOLEAN,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_entity_template_aud_revinfo FOREIGN KEY (rev) REFERENCES envers_transaction_log (rev) ON DELETE CASCADE
);

CREATE INDEX idx_entity_template_aud_rev ON entity_template_aud (rev);

CREATE TABLE property_definition_aud
(
    id              UUID   NOT NULL,
    rev             BIGINT NOT NULL,
    revtype         SMALLINT,
    name            VARCHAR(255),
    name_mod        BOOLEAN,
    description     TEXT,
    description_mod BOOLEAN,
    type            VARCHAR(50),
    type_mod        BOOLEAN,
    required        BOOLEAN,
    required_mod    BOOLEAN,
    rules_id        UUID,
    rules_mod    BOOLEAN,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_property_definition_aud_revinfo FOREIGN KEY (rev) REFERENCES envers_transaction_log (rev) ON DELETE CASCADE
);

CREATE INDEX idx_property_definition_aud_rev ON property_definition_aud (rev);

CREATE TABLE property_rules_aud
(
    id              UUID   NOT NULL,
    rev             BIGINT NOT NULL,
    revtype         SMALLINT,
    format          VARCHAR(50),
    format_mod      BOOLEAN,
    enum_values     TEXT[],
    enum_values_mod BOOLEAN,
    regex           VARCHAR(500),
    regex_mod       BOOLEAN,
    max_length      INTEGER,
    max_length_mod  BOOLEAN,
    min_length      INTEGER,
    min_length_mod  BOOLEAN,
    max_value       INTEGER,
    max_value_mod   BOOLEAN,
    min_value       INTEGER,
    min_value_mod   BOOLEAN,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_property_rules_aud_revinfo FOREIGN KEY (rev) REFERENCES envers_transaction_log (rev) ON DELETE CASCADE
);

CREATE INDEX idx_property_rules_aud_rev ON property_rules_aud (rev);

CREATE TABLE relation_definition_aud
(
    id                             UUID   NOT NULL,
    rev                            BIGINT NOT NULL,
    revtype                        SMALLINT,
    name                           VARCHAR(255),
    name_mod                       BOOLEAN,
    target_template_identifier     VARCHAR(255),
    target_template_identifier_mod BOOLEAN,
    required                       BOOLEAN,
    required_mod                   BOOLEAN,
    to_many                        BOOLEAN,
    to_many_mod                    BOOLEAN,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_relation_definition_aud_revinfo FOREIGN KEY (rev) REFERENCES envers_transaction_log (rev) ON DELETE CASCADE
);

CREATE INDEX idx_relation_definition_aud_rev ON relation_definition_aud (rev);

CREATE TABLE entity_properties_aud
(
    rev             BIGINT NOT NULL,
    revtype         SMALLINT,
    entity_id       UUID   NOT NULL,
    entity_id_mod   BOOLEAN,
    property_id     UUID   NOT NULL,
    property_id_mod BOOLEAN,
    PRIMARY KEY (rev, entity_id, property_id),
    CONSTRAINT fk_entity_properties_aud_revinfo FOREIGN KEY (rev) REFERENCES envers_transaction_log (rev) ON DELETE CASCADE
);

CREATE INDEX idx_entity_properties_aud_entity_id ON entity_properties_aud (entity_id);

CREATE TABLE entity_relations_aud
(
    rev             BIGINT NOT NULL,
    revtype         SMALLINT,
    entity_id       UUID   NOT NULL,
    entity_id_mod   BOOLEAN,
    relation_id     UUID   NOT NULL,
    relation_id_mod BOOLEAN,
    PRIMARY KEY (rev, entity_id, relation_id),
    CONSTRAINT fk_entity_relations_aud_revinfo FOREIGN KEY (rev) REFERENCES envers_transaction_log (rev) ON DELETE CASCADE
);

CREATE INDEX idx_entity_relations_aud_entity_id ON entity_relations_aud (entity_id);

CREATE TABLE relation_target_entities_aud
(
    rev                          BIGINT       NOT NULL,
    revtype                      SMALLINT,
    relation_id                  UUID         NOT NULL,
    relation_id_mod              BOOLEAN,
    target_entity_identifier     VARCHAR(255) NOT NULL,
    target_entity_identifier_mod BOOLEAN,
    PRIMARY KEY (rev, relation_id, target_entity_identifier),
    CONSTRAINT fk_relation_target_entities_aud_revinfo FOREIGN KEY (rev) REFERENCES envers_transaction_log (rev) ON DELETE CASCADE
);

CREATE INDEX idx_relation_target_entities_aud_relation_id ON relation_target_entities_aud (relation_id);

CREATE TABLE entity_template_properties_definitions_aud
(
    rev                           BIGINT NOT NULL,
    revtype                       SMALLINT,
    entity_template_id            UUID   NOT NULL,
    entity_template_id_mod        BOOLEAN,
    properties_definitions_id     UUID   NOT NULL,
    properties_definitions_id_mod BOOLEAN,
    PRIMARY KEY (rev, entity_template_id, properties_definitions_id),
    CONSTRAINT fk_entity_template_properties_definitions_aud_revinfo FOREIGN KEY (rev) REFERENCES envers_transaction_log (rev) ON DELETE CASCADE
);

CREATE INDEX idx_entity_template_properties_definitions_aud_template_id ON entity_template_properties_definitions_aud (entity_template_id);

CREATE TABLE entity_template_relations_definitions_aud
(
    rev                          BIGINT NOT NULL,
    revtype                      SMALLINT,
    entity_template_id           UUID   NOT NULL,
    entity_template_id_mod       BOOLEAN,
    relations_definitions_id     UUID   NOT NULL,
    relations_definitions_id_mod BOOLEAN,
    PRIMARY KEY (rev, entity_template_id, relations_definitions_id),
    CONSTRAINT fk_entity_template_relations_definitions_aud_revinfo FOREIGN KEY (rev) REFERENCES envers_transaction_log (rev) ON DELETE CASCADE
);

CREATE INDEX idx_entity_template_relations_definitions_aud_template_id ON entity_template_relations_definitions_aud (entity_template_id);
