name: Build and Push to Docker Hub

on: # yamllint disable-line rule:truthy
  release:
    types: [released]  #  Trigger only for stable and public releases
  workflow_dispatch:  # Allow manual triggering of the workflow
    inputs:
      tag_name:
        description: 'Tag name for the release (e.g., v1.0.0)'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and Push Docker Image
    timeout-minutes: 20
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  #  v7.0.1
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.tag_name || github.event.inputs.tag_name }}
      - name: Set up JDK 25
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961  #  v5.7.0
        with:
          distribution: 'temurin'
          java-version: 25
          cache: maven
          overwrite-settings: false
      - name: Compile
        id: compile
        run: mvn clean verify
      - name: Login to Docker Hub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f  #  v4.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e  #  v4.3.0
      - name: Build and push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a  #  v7.3.0
        with:
          context: .
          push: true
          sbom: true
          provenance: mode=max
          tags: decathlon/internal-developer-platform:${{ github.event.release.tag_name || github.event.inputs.tag_name }},decathlon/internal-developer-platform:latest
      - name: Update repo description
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: decathlon/internal-developer-platform
